Disable requests prefetch flag
python-requests v0.13.6 switched Request class argument `prefetch` to be
enabled by default. See https://github.com/kennethreitz/requests/commit/3c0b94047c1ccfca4ac4f2fe32afef0ae314094e

With that change in requests library, `Response.iterlines` fails like:

Traceback (most recent call last):
  File "t.py", line 5, in <module>
    for job in jobs:
  File "/home/daniel/src/python-scrapinghub/scrapinghub.py", line 208, in __iter__
    self._load_jobs()
  File "/home/daniel/src/python-scrapinghub/scrapinghub.py", line 233, in _load_jobs
    status_line = result.next()
  File "/home/daniel/src/python-scrapinghub/scrapinghub.py", line 116, in <genexpr>
    return (json.loads(line) for line in response.iter_lines())
  File "/home/daniel/src/requests/requests/models.py", line 740, in iter_lines
    decode_unicode=decode_unicode):
  File "/home/daniel/src/requests/requests/models.py", line 712, in iter_content
    'The content for this response was already consumed'
RuntimeError: The content for this response was already consumed